import { NavItem } from '@/types';
export type Role = 'patient' | 'caregiver' | 'admin' | "doctor";



export const roleNavItems: Record<Role, NavItem[]> = {
  patient: [
    {
      title: 'Dashboard',
      url: '/dashboard/overview',
      icon: 'dashboard',
      shortcut: ['d', 'd'],
      isActive: false,
      items: [],
    },
    // Top-level (not nested) so icons stay clickable in collapsed sidebar.
    {
      title: 'Predictive AI',
      url: '/dashboard/predictive-ai',
      icon: 'predictiveAi',
      shortcut: ['m', 'm'],
      isActive: false,
      items: [],
    },
    {
      title: 'AI Chat',
      url: '/dashboard/ai',
      icon: 'aiChat',
      shortcut: ['l', 'l'],
      isActive: false,
      items: [],
    },
    {
      title: 'Chat',
      url: '/dashboard/chat',
      icon: 'chat',
      shortcut: ['c', 'c'],
      isActive: false,
      items: [],
    },
    {
      title: 'Alerts',
      url: '/dashboard/alert',
      icon: 'alertTriangle',
      shortcut: ['a', 'l'],
      isActive: false,
      items: [],
    },
    {
      title: 'medicine',
      url: '/dashboard/medicine',
      icon: 'drugs',
      shortcut: ['m', 'e'],
      isActive: false,
      items: [],
    },
    {
      title: 'Medical Profile',
      url: '/dashboard/medical-profile',
      icon: 'billing',
      isActive: true,
      items: [],
    },
    {
      title: 'Health KPIs',
      url: '/dashboard/health-kpis',
      icon: 'healthKpi',
      isActive: false,
      items: [],
    },
  ],
  caregiver: [
    {
      title: 'Dashboard',
      url: '/dashboard/caregiver-overview',
      icon: 'dashboard',
      shortcut: ['d', 'd'],
      isActive: false,
      items: [],
    },
    {
      title: 'Patients',
      url: '/dashboard/my-patients',
      icon: 'user',
      shortcut: ['p', 't'],
      isActive: false,
      items: [],
    },
    {
      title: 'Fall Camera Logs',
      url: '/dashboard/fall-reports',
      icon: 'camera',
      shortcut: ['f', 'r'],
      isActive: false,
      items: [],
    },
    {
      title: 'Patient Alerts',
      url: '/dashboard/patient-alert',
      icon: 'alertTriangle',
      shortcut: ['a', 'l'],
      isActive: false,
      items: [],
    },
    {
      title: 'AI Chat',
      url: '/dashboard/ai',
      icon: 'aiChat',
      shortcut: ['a', 'i'],
      isActive: false,
      items: [],
    },
    {
      title: 'Chat',
      url: '/dashboard/chat',
      icon: 'chat',
      shortcut: ['c', 'c'],
      isActive: false,
      items: [],
    },
  ],
  doctor: [
    {
      title: 'Dashboard',
      url: '/dashboard/doctor-overview',
      icon: 'dashboard',
      shortcut: ['d', 'd'],
      isActive: false,
      items: [],
    },
    {
      title: 'Patients',
      url: '/dashboard/patients',
      icon: 'user',
      shortcut: ['p', 't'],
      isActive: false,
      items: [],
    },
    {
      title: 'Fall Camera Logs',
      url: '/dashboard/fall-reports',
      icon: 'camera',
      shortcut: ['f', 'r'],
      isActive: false,
      items: [],
    },
    {
      title: 'Patient Alerts',
      url: '/dashboard/patient-alert',
      icon: 'alertTriangle',
      shortcut: ['a', 'l'],
      isActive: false,
      items: [],
    },
    {
      title: 'AI Chat',
      url: '/dashboard/ai',
      icon: 'aiChat',
      shortcut: ['a', 'i'],
      isActive: false,
      items: [],
    },
    {
      title: 'Chat',
      url: '/dashboard/chat',
      icon: 'chat',
      shortcut: ['c', 'c'],
      isActive: false,
      items: [],
    },
  ],
  admin: [
    {
      title: 'Users',
      url: '/dashboard/users',
      icon: 'usersGroup',
      shortcut: ['d', 'd'],
      isActive: false,
      items: [],
    },
    {
      title: 'Clinics',
      url: '/dashboard/clinics',
      icon: 'clinic',
      shortcut: ['c', 'l'],
      isActive: false,
      items: [],
    },
    {
      title: 'Billing',
      url: '/dashboard/billing',
      icon: 'billing',
      shortcut: ['b', 'b'],
      isActive: false,
      items: [],
    },
    {
      title: 'Relations',
      url: '/dashboard/relations',
      icon: 'relations',
      shortcut: ['r', 'r'],
      isActive: false,
      items: [],
    },
    {
      title: 'Chatrooms',
      url: '/dashboard/chatrooms',
      icon: 'chat',
      shortcut: ['c', 'r'],
      isActive: false,
      items: [],
    },
    {
      title: 'Chat Sessions',
      url: '/dashboard/chat-sessions',
      icon: 'aiChat',
      shortcut: ['c', 's'],
      isActive: false,
      items: [],
    },
    {
      title: 'Chat',
      url: '/dashboard/chat',
      icon: 'chat',
      shortcut: ['c', 'c'],
      isActive: false,
      items: [],
    },
  ],
};


